/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/app/AppAlert.vue')['default']
    'AppAlert v.1': typeof import('./src/components/app/AppAlert v.1.vue')['default']
    AppError: typeof import('./src/components/app/AppError.vue')['default']
    AppGrid: typeof import('./src/components/app/AppGrid.vue')['default']
    AppLoading: typeof import('./src/components/app/AppLoading.vue')['default']
    AppModal: typeof import('./src/components/app/AppModal.vue')['default']
    AppPagination: typeof import('./src/components/app/AppPagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'v.1': typeof import('./src/components/app/AppAlert v.1.vue')['default']
  }
}
